FROM golang:1.25-alpine AS builder
WORKDIR /go
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 go build -o /notifier ./cmd/notifier

FROM alpine:3.19
WORKDIR /app
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /notifier ./notifier
CMD ["./notifier"]
