definitions:
  handlers.Todo:
    properties:
      done:
        type: boolean
      id:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/create:
    post:
      consumes:
      - application/json
      description: create new todo
      parameters:
      - description: Todo object
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/handlers.Todo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Todo'
      summary: Create todo
      tags:
      - todos
  /api/todos:
    get:
      description: get list of todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.Todo'
            type: array
      summary: Get all todos
      tags:
      - todos
swagger: "2.0"
